import { SettingsIcon } from "lucide-react";
import React, { useRef } from "react";
import { InfoBubble } from "./components/InfoBubble";
import { Background } from "./components/Background";
import { GridPattern } from "./components/GridPattern";
import { AnimatedCurvedLines } from "./components/AnimatedCurvedLines";
import { Logo } from "./components/Logo";
import { PageHeading } from "./components/PageHeading";
import { CTAButton } from "./components/CTAButton";

/**
 * Props for the IntroFlow component
 */
export interface IntroFlowProps {
  onOpenSettings: () => void;
}

/**
 * Intro Flow Component
 *
 * Shows when the user hasn't selected a provider yet.
 * Guides them to configure a provider in settings.
 */
export const IntroFlow: React.FC<IntroFlowProps> = ({ onOpenSettings }) => {
  const containerRef = useRef<HTMLDivElement>(null);

  return (
    <div
      ref={containerRef}
      className="flex min-h-screen items-center justify-center bg-gray-950 p-4 relative overflow-hidden"
    >
      {/* Animated gradient background */}
      <Background className="bg-pink-500/10" />

      {/* Subtle grid pattern */}
      <GridPattern />

      {/* Subtle curved orange lines in background with parallax */}
      <AnimatedCurvedLines containerRef={containerRef} />

      <div className="relative max-w-2xl w-full">
        {/* Logo */}
        <Logo className="mb-8 mt-10" size={80} />

        {/* Heading */}
        <PageHeading
          title="Welcome to Intent Prompts"
          description="Intent Prompts helps you clarify what you actually want from AI. Connect a provider to begin."
          className="mb-12"
        />

        {/* Steps */}
        <div className="mb-8 w-full max-w-md mx-auto">
          <div className="space-y-4">
            <InfoBubble
              number={1}
              title="Choose Provider"
              description="OpenAI, Anthropic, or Google"
            />
            <InfoBubble
              number={2}
              title="Add API Key"
              description="Generated by your provider"
            />
            <InfoBubble
              number={3}
              title="Start Prompting"
              description="We will help refine prompts for you"
            />
          </div>
        </div>

        {/* CTA */}
        <CTAButton
          onClick={onOpenSettings}
          label="Go to Settings"
          icon={SettingsIcon}
          helperText="Change settings anytime"
        />
      </div>
    </div>
  );
};
